baseURL = 'https://billypetersson.github.io/peterssontech.net/'
languageCode = 'en-us'
title = 'Billy Petersson - IT Professional Portfolio'

[params]
  author = 'Billy Petersson'
  description = 'Professional IT portfolio showcasing expertise in software development, system administration, and technology solutions'
  keywords = ['IT Professional', 'Software Developer', 'System Administrator', 'Technology Solutions', 'Portfolio']
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 2
  [[menu.main]]
    name = 'Skills'
    url = '/skills/'
    weight = 3
  [[menu.main]]
    name = 'Experience'
    url = '/experience/'
    weight = 4
  [[menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 5
  [[menu.main]]
    name = 'Blog'
    url = '/blog/'
    weight = 6
  [[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 7

[params.social]
  linkedin = 'https://linkedin.com/in/billy-petersson'
  github = 'https://github.com/billy-petersson'
  email = 'billy@peterssontech.net'

# SEO and performance settings
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[sitemap]
  changeFreq = 'weekly'
  priority = 0.5

[imaging]
  quality = 85
  resampleFilter = 'Lanczos'

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  
[outputs]
  home = ['HTML', 'RSS', 'JSON']
  page = ['HTML']
  section = ['HTML', 'RSS']

[outputFormats]
  [outputFormats.RSS]
    mediaType = 'application/rss+xml'
    baseName = 'index'
    
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true
    anonymizeIP = true
    useSessionStorage = true
